-- Migración: Renombrar claves de ConfiguracionSistema para estandarización a español
-- Fecha: 2026-01-29
-- Autor: Antigravity

BEGIN TRANSACTION;

-- LANZADOR
UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_REPETICIONES_ROBOT'
WHERE Clave = 'LANZADOR_BOT_INPUT_VUELTAS';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_UMBRAL_ALERTAS_ERROR_412'
WHERE Clave = 'LANZADOR_UMBRAL_ALERTAS_412';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_HABILITAR_SINCRONIZACION'
WHERE Clave = 'LANZADOR_HABILITAR_SYNC';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_CONCILIADOR_TAMANO_LOTE'
WHERE Clave = 'LANZADOR_CONCILIADOR_BATCH_SIZE';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_PARAMETROS_PREDETERMINADOS_JSON'
WHERE Clave = 'LANZADOR_PARAMETROS_DEFAULT_JSON';

-- CONCILIADOR (ahora bajo prefijo LANZADOR_)
UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_CONCILIADOR_DIAS_TOLERANCIA_ESTADO_UNKNOWN'
WHERE Clave = 'CONCILIADOR_DIAS_TOLERANCIA_UNKNOWN';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_CONCILIADOR_MENSAJE_INFERIDO'
WHERE Clave = 'CONCILIADOR_MENSAJE_INFERIDO';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'LANZADOR_CONCILIADOR_MAX_INTENTOS_INFERENCIA'
WHERE Clave = 'CONCILIADOR_MAX_INTENTOS_INFERENCIA';

-- BALANCEADOR
UPDATE dbo.ConfiguracionSistema
SET Clave = 'BALANCEADOR_PERIODO_ENFRIAMIENTO_SEG'
WHERE Clave = 'BALANCEADOR_COOLING_PERIOD_SEG' OR Clave = 'BALANCEADOR_POOL_COOLDOWN_SEG';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'BALANCEADOR_TICKETS_PREDETERMINADOS_POR_EQUIPO'
WHERE Clave = 'BALANCEADOR_DEFAULT_TICKETS_POR_EQUIPO';

-- EMAIL Y ALERTAS
UPDATE dbo.ConfiguracionSistema
SET Clave = 'EMAIL_DESTINATARIOS'
WHERE Clave = 'EMAIL_RECIPIENTS';

-- INTERFAZ WEB (Umbrales de Analítica)
UPDATE dbo.ConfiguracionSistema
SET Clave = 'INTERFAZ_WEB_UMBRAL_EJECUCION_DEMORADA_MINUTOS'
WHERE Clave = 'UMBRAL_EJECUCION_DEMORADA_MINUTOS';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'INTERFAZ_WEB_FACTOR_UMBRAL_DINAMICO'
WHERE Clave = 'FACTOR_UMBRAL_DINAMICO';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'INTERFAZ_WEB_PISO_UMBRAL_DINAMICO_MINUTOS'
WHERE Clave = 'PISO_UMBRAL_DINAMICO_MINUTOS';

UPDATE dbo.ConfiguracionSistema
SET Clave = 'INTERFAZ_WEB_FILTRO_EJECUCIONES_CORTAS_MINUTOS'
WHERE Clave = 'FILTRO_EJECUCIONES_CORTAS_MINUTOS';

COMMIT;
