-- Migración: Renombrar claves de ConfiguracionSistema a nueva convención
-- Convención: {SERVICIO}_{TEMA}_{ACCION}[_{UNIDAD}]
-- Fecha: 2026-01-30
-- Versión: v2
--
-- NOTA: Este script es idempotente y solo renombra si la clave antigua existe
--       y la nueva no existe. No pierde datos.

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

PRINT '=== Iniciando migración de nombres de claves de configuración ==='
PRINT 'Convención: {SERVICIO}_{TEMA}_{ACCION}[_{UNIDAD}]'
PRINT ''

-- Procedimiento auxiliar para renombrar claves de forma segura
CREATE OR ALTER PROCEDURE #RenombrarClave
    @ClaveAntigua VARCHAR(100),
    @ClaveNueva VARCHAR(100)
AS
BEGIN
    -- Solo renombrar si la antigua existe y la nueva NO existe
    IF EXISTS (SELECT 1 FROM [dbo].[ConfiguracionSistema] WHERE Clave = @ClaveAntigua)
       AND NOT EXISTS (SELECT 1 FROM [dbo].[ConfiguracionSistema] WHERE Clave = @ClaveNueva)
    BEGIN
        UPDATE [dbo].[ConfiguracionSistema]
        SET Clave = @ClaveNueva,
            FechaActualizacion = GETDATE()
        WHERE Clave = @ClaveAntigua;
        PRINT '✓ Renombrada: ' + @ClaveAntigua + ' → ' + @ClaveNueva;
    END
    ELSE IF EXISTS (SELECT 1 FROM [dbo].[ConfiguracionSistema] WHERE Clave = @ClaveNueva)
    BEGIN
        PRINT '⊘ Ya existe (omitida): ' + @ClaveNueva;
    END
    ELSE
    BEGIN
        PRINT '○ No encontrada (omitida): ' + @ClaveAntigua;
    END
END
GO

-- ===== LANZADOR =====
PRINT ''
PRINT '--- LANZADOR ---'
EXEC #RenombrarClave 'LANZADOR_HABILITAR_SINCRONIZACION', 'LANZADOR_SYNC_HABILITAR';
EXEC #RenombrarClave 'LANZADOR_HABILITAR_SYNC', 'LANZADOR_SYNC_HABILITAR';
EXEC #RenombrarClave 'LANZADOR_INTERVALO_SINCRONIZACION_SEG', 'LANZADOR_SYNC_INTERVALO_SEG';
EXEC #RenombrarClave 'LANZADOR_INTERVALO_LANZAMIENTO_SEG', 'LANZADOR_CICLO_INTERVALO_SEG';
EXEC #RenombrarClave 'LANZADOR_INTERVALO_CONCILIACION_SEG', 'LANZADOR_CONCILIACION_INTERVALO_SEG';
EXEC #RenombrarClave 'LANZADOR_CONCILIADOR_TAMANO_LOTE', 'LANZADOR_CONCILIACION_LOTE_TAMANO';
EXEC #RenombrarClave 'LANZADOR_CONCILIADOR_BATCH_SIZE', 'LANZADOR_CONCILIACION_LOTE_TAMANO';
EXEC #RenombrarClave 'LANZADOR_CONCILIADOR_DIAS_TOLERANCIA_ESTADO_UNKNOWN', 'LANZADOR_CONCILIACION_UNKNOWN_TOLERANCIA_DIAS';
EXEC #RenombrarClave 'CONCILIADOR_DIAS_TOLERANCIA_UNKNOWN', 'LANZADOR_CONCILIACION_UNKNOWN_TOLERANCIA_DIAS';
EXEC #RenombrarClave 'LANZADOR_CONCILIADOR_MENSAJE_INFERIDO', 'LANZADOR_CONCILIACION_INFERENCIA_MENSAJE';
EXEC #RenombrarClave 'CONCILIADOR_MENSAJE_INFERIDO', 'LANZADOR_CONCILIACION_INFERENCIA_MENSAJE';
EXEC #RenombrarClave 'LANZADOR_CONCILIADOR_MAX_INTENTOS_INFERENCIA', 'LANZADOR_CONCILIACION_INFERENCIA_MAX_INTENTOS';
EXEC #RenombrarClave 'CONCILIADOR_MAX_INTENTOS_INFERENCIA', 'LANZADOR_CONCILIACION_INFERENCIA_MAX_INTENTOS';
EXEC #RenombrarClave 'LANZADOR_MAX_REINTENTOS_DEPLOY', 'LANZADOR_DEPLOY_REINTENTOS_MAX';
EXEC #RenombrarClave 'LANZADOR_DELAY_REINTENTO_DEPLOY_SEG', 'LANZADOR_DEPLOY_REINTENTO_DELAY_SEG';
EXEC #RenombrarClave 'LANZADOR_REPETICIONES_ROBOT', 'LANZADOR_ROBOT_REPETICIONES';
EXEC #RenombrarClave 'LANZADOR_BOT_INPUT_VUELTAS', 'LANZADOR_ROBOT_REPETICIONES';
EXEC #RenombrarClave 'LANZADOR_MAX_WORKERS', 'LANZADOR_WORKERS_MAX';
EXEC #RenombrarClave 'LANZADOR_UMBRAL_ALERTAS_ERROR_412', 'LANZADOR_ALERTAS_ERROR_412_UMBRAL';
EXEC #RenombrarClave 'LANZADOR_UMBRAL_ALERTAS_412', 'LANZADOR_ALERTAS_ERROR_412_UMBRAL';
EXEC #RenombrarClave 'LANZADOR_PARAMETROS_PREDETERMINADOS_JSON', 'LANZADOR_ROBOT_PARAMETROS_JSON';
EXEC #RenombrarClave 'LANZADOR_PARAMETROS_DEFAULT_JSON', 'LANZADOR_ROBOT_PARAMETROS_JSON';

-- ===== BALANCEADOR =====
PRINT ''
PRINT '--- BALANCEADOR ---'
EXEC #RenombrarClave 'BALANCEADOR_PERIODO_ENFRIAMIENTO_SEG', 'BALANCEADOR_POOL_ENFRIAMIENTO_SEG';
EXEC #RenombrarClave 'BALANCEADOR_COOLING_PERIOD_SEG', 'BALANCEADOR_POOL_ENFRIAMIENTO_SEG';
EXEC #RenombrarClave 'BALANCEADOR_POOL_COOLDOWN_SEG', 'BALANCEADOR_POOL_ENFRIAMIENTO_SEG';
EXEC #RenombrarClave 'BALANCEADOR_INTERVALO_CICLO_SEG', 'BALANCEADOR_CICLO_INTERVALO_SEG';
EXEC #RenombrarClave 'BALANCEADOR_PROVEEDORES_CARGA', 'BALANCEADOR_CARGA_PROVEEDORES';
EXEC #RenombrarClave 'BALANCEADOR_TICKETS_PREDETERMINADOS_POR_EQUIPO', 'BALANCEADOR_TICKETS_DEFAULT_POR_EQUIPO';
EXEC #RenombrarClave 'BALANCEADOR_DEFAULT_TICKETS_POR_EQUIPO', 'BALANCEADOR_TICKETS_DEFAULT_POR_EQUIPO';
EXEC #RenombrarClave 'BALANCEO_PREEMPTION_MODE', 'BALANCEADOR_PREEMPTION_HABILITAR';

-- ===== INTERFAZ_WEB =====
PRINT ''
PRINT '--- INTERFAZ_WEB ---'
EXEC #RenombrarClave 'INTERFAZ_WEB_SESSION_TIMEOUT_MIN', 'INTERFAZ_WEB_SESION_TIMEOUT_MIN';
EXEC #RenombrarClave 'INTERFAZ_WEB_MAX_UPLOAD_SIZE_MB', 'INTERFAZ_WEB_UPLOAD_MAX_MB';
EXEC #RenombrarClave 'INTERFAZ_WEB_UMBRAL_EJECUCION_DEMORADA_MINUTOS', 'INTERFAZ_WEB_EJECUCION_DEMORA_UMBRAL_MIN';
EXEC #RenombrarClave 'INTERFAZ_WEB_FACTOR_UMBRAL_DINAMICO', 'INTERFAZ_WEB_EJECUCION_UMBRAL_FACTOR';
EXEC #RenombrarClave 'INTERFAZ_WEB_PISO_UMBRAL_DINAMICO_MINUTOS', 'INTERFAZ_WEB_EJECUCION_UMBRAL_PISO_MIN';
EXEC #RenombrarClave 'INTERFAZ_WEB_FILTRO_EJECUCIONES_CORTAS_MINUTOS', 'INTERFAZ_WEB_EJECUCION_FILTRO_CORTAS_MIN';
EXEC #RenombrarClave 'INTERFAZ_WEB_AA_USER', 'INTERFAZ_WEB_AA_USUARIO';

-- ===== EMAIL =====
PRINT ''
PRINT '--- EMAIL ---'
EXEC #RenombrarClave 'EMAIL_RECIPIENTS', 'EMAIL_DESTINATARIOS';

-- ===== MAPA_ROBOTS =====
PRINT ''
PRINT '--- OTROS ---'
EXEC #RenombrarClave 'MAPA_ROBOTS', 'ROBOTS_MAPA_JSON';

-- Limpieza
DROP PROCEDURE #RenombrarClave;
GO

PRINT ''
PRINT '=== Migración completada ==='
PRINT 'Los nombres antiguos siguen funcionando gracias al fallback en ConfigManager.'
GO
