# sam/web/frontend/shared/__init__.py
"""Componentes compartidos y reutilizables."""

from .async_content import AsyncContent, EmptyState, ErrorAlert, LoadingSpinner
from .common_components import (
    ActionMenu,
    ConfirmationModal,
    ErrorMessage,
    PageWithLayout,
    Pagination,
    ThemeSwitcher,
)
from .data_table import DataTable
from .styles import (
    BUTTON_DANGER,
    BUTTON_OUTLINE,
    BUTTON_OUTLINE_DANGER,
    BUTTON_OUTLINE_SECONDARY,
    BUTTON_PRIMARY,
    BUTTON_SECONDARY,
    CARD,
    CARDS_CONTAINER,
    CARDS_CONTAINER_POOLS,
    CARDS_CONTAINER_ROBOTS,
    COLLAPSIBLE_PANEL,
    COLLAPSIBLE_PANEL_EXPANDED,
    CONTAINER,
    DASHBOARD_CONTROLS,
    GRID,
    MASTER_CONTROLS_GRID,
    MOBILE_CONTROLS_TOGGLE,
    POOL_CARD,
    POOL_CARD_BODY,
    POOL_CARD_FOOTER,
    POOL_CARD_HEADER,
    PRIMARY,
    ROBOT_CARD,
    ROBOT_CARD_BODY,
    ROBOT_CARD_FOOTER,
    ROBOT_CARD_HEADER,
    SCHEDULE_CARD,
    SEARCH_INPUT,
    SECONDARY,
    STATUS_EJECUCION_DEMANDA,
    STATUS_EJECUCION_PROGRAMADO,
    STATUS_RUNNING,
    STATUS_STOPPED,
    STATUS_UNKNOWN,
    TAG,
    TAG_SECONDARY,
    TABLE_CONTAINER,
)

__all__ = [
    # Componentes async
    "AsyncContent",
    "EmptyState",
    "ErrorAlert",
    "LoadingSpinner",
    # Componentes comunes
    "ActionMenu",
    "ConfirmationModal",
    "ErrorMessage",
    "PageWithLayout",
    "Pagination",
    "ThemeSwitcher",
    # DataTable
    "DataTable",
    # Estilos
    "BUTTON_PRIMARY",
    "BUTTON_SECONDARY",
    "BUTTON_DANGER",
    "BUTTON_OUTLINE",
    "BUTTON_OUTLINE_SECONDARY",
    "BUTTON_OUTLINE_DANGER",
    "STATUS_RUNNING",
    "STATUS_STOPPED",
    "STATUS_UNKNOWN",
    "STATUS_EJECUCION_PROGRAMADO",
    "STATUS_EJECUCION_DEMANDA",
    "TAG",
    "TAG_SECONDARY",
    "CARD",
    "GRID",
    "CONTAINER",
    "CARDS_CONTAINER",
    "CARDS_CONTAINER_ROBOTS",
    "CARDS_CONTAINER_POOLS",
    "TABLE_CONTAINER",
    "ROBOT_CARD",
    "ROBOT_CARD_HEADER",
    "ROBOT_CARD_BODY",
    "ROBOT_CARD_FOOTER",
    "POOL_CARD",
    "POOL_CARD_HEADER",
    "POOL_CARD_BODY",
    "POOL_CARD_FOOTER",
    "SCHEDULE_CARD",
    "DASHBOARD_CONTROLS",
    "CONTROLS_HEADER",
    "MASTER_CONTROLS_GRID",
    "COLLAPSIBLE_PANEL",
    "COLLAPSIBLE_PANEL_EXPANDED",
    "MOBILE_CONTROLS_TOGGLE",
    "SEARCH_INPUT",
    "PRIMARY",
    "SECONDARY",
]

