SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ConfiguracionSistema]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ConfiguracionSistema](
	[Clave] [varchar](50) NOT NULL,
	[Valor] [varchar](255) NULL,
	[Descripcion] [varchar](500) NULL,
	[FechaActualizacion] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[Clave] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_PADDING OFF
GO
